# Los fundamentos de Arrays en NumPy

Esta sección presentará varios ejemplos del uso de la manipulación de arreglos NumPy para acceder a datos y subarreglos, y para dividir, remodelar y unir los arreglos. 

Categorías de manipulaciones básicas en arrays de Numpy:

    ¶ Atributos.
    ¶ Indexación.
    ¶ Rebanado/Corte.
    ¶ Remodelación.
    ¶ Unión y división.


## Atributos de arrays ¶

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [2]:
#Numero de dimensiones
print("x3 numero de dim con ndim: ", x3.ndim)
#Tamaño de cada dimensión.
print("x3 forma con shape:", x3.shape) 
#Tamaño total de array
print("x3 tamaño con size: ", x3.size)

x3 numero de dim con ndim:  3
x3 forma con shape: (3, 4, 5)
x3 tamaño con size:  60


In [3]:
#tipo de dato de array
print("dtype:", x3.dtype)

dtype: int64


In [4]:
# itemsize enumera el tamaño (en bytes) de cada elemento del array
print("itemsize:", x3.itemsize, "bytes")
# nbytes enumera el tamaño total (en bytes) del array:
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Indexación de array ¶

Acceso al valor usando indices entre corchetes

In [5]:
print(f'Apartir de x1:  {x1}')
print(f'Se accede al primer y ultimo elemento de x1: \n  x1[0]={x1[0]} y x1[0]={x1[x1.size-1]}')

Apartir de x1:  [5 0 3 3 7 9]
Se accede al primer y ultimo elemento de x1: 
  x1[0]=5 y x1[0]=9


Tambien puede indexar desde el final del array usando índices negativos.

In [6]:
print(f'penultimo: {x1[-2]}')
print(f'ultimo:  {x1[-1]}')

penultimo: 7
ultimo:  9


En un array multidimensional, se puede acceder y modificar sus elementos mediante una tupla de índices.

In [16]:
print(f'x2:\n{x2}')

x2:
[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 11]]


In [17]:
x2 [ 0 ,  0 ]

3

In [20]:
x2 [ 2 ,  0 ] 

1

In [19]:
x2 [ -1 ,  - 1 ] = 11

Los valores también se pueden modificar utilizando las notaciones de índice anteriores.

In [21]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 11]])

Los arrays NumPy tienen un tipo fijo. Esto significa, por ejemplo, que si intenta insertar un valor de coma flotante en una matriz de enteros, el valor se truncará silenciosamente. ¡No se deje sorprender por este comportamiento!

In [22]:
x1

array([5, 0, 3, 3, 7, 9])

In [23]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Rebanado/Corte ¶ 

Para acceder a un subarrays de x use:

    x[start:stop:step]

Si alguno de estos no se especifica, adoptan valores predeterminados "start=0, stop=size of dimension, step=1.

### Subarreglos unidimensionales

In [73]:
x= np.random.randint(10, size=10)  
print(f'x:   {x}\n')

print(f'Primeros 5 elementos: {x[:5]}') 
print(f'Elementos despues del indice 5: {x[5:]}')
#x[4:7]=[6,5,4]
print(f'sub-array medio: { x[4:7]}')

print(f'De 2 en 2 {x[::2]}')

print(f'De 2 en 2 iniciando en x[1] {x[1::2]}')

print(f'x:   {x}')

x:   [1 5 9 3 0 5 0 1 2 4]

Primeros 5 elementos: [1 5 9 3 0]
Elementos despues del indice 5: [5 0 1 2 4]
sub-array medio: [0 5 0]
De 2 en 2 [1 9 0 0 2]
De 2 en 2 iniciando en x[1] [5 3 5 1 4]
x:   [1 5 9 3 0 5 0 1 2 4]


Un caso potencialmente confuso es cuando el step tiene valor negativo. En este caso, los valores predeterminados para start y stop se intercambian. Esto se convierte en una forma conveniente de invertir una matriz:

In [74]:
#x=x[::-1]   # todos los elementos, invertidos 
x[::-1]

array([4, 2, 1, 0, 5, 0, 3, 9, 5, 1])

In [79]:
#primero accede a start luego invierte y salta hacia atras
x[8::-2]

array([2, 0, 0, 9, 1])

### Subconjuntos multidimensionales 

Los sectores multidimensionales funcionan de la misma manera, con varios sectores separados por comas. Por ejemplo: 

In [80]:
x2 

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 11]])

In [86]:
print(f'Obtener 2f y 3c de x2:\n {x2 [:2 ,  :3 ]} ')  # dos filas, tres columnas 
print(f'Obtener allf y cada 2c de allc de x2:\n {x2 [ : , ::2 ]}' )   # todas las filas, cada dos columnas de todos  


Obtener 2f y 3c de x2:
 [[3 5 2]
 [7 6 8]] 
Obtener allf y cada 2c de allc de x2:
 [[3 2]
 [7 8]
 [1 7]]


Las dimensiones del subarreglo pueden incluso invertirse juntas:

In [87]:
x2 [ ::-1 , ::-1 ] 

array([[11,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]])

### Accediendo a filas y columnas de arreglos 

Una rutina comúnmente necesaria es acceder a filas o columnas individuales de una matriz. Esto se puede hacer combinando la indexación y el corte, utilizando un segmento vacío marcado con dos puntos (:) 

In [94]:
print(f'Primer Columna de x2:\n{x2[:, 0]}')
print(f'Primer Fila de x2:\n{x2[0,:]}')
#print(f'Primer Fila de x2":\n{x2[0]}')


Primer Columna de x2:
[3 7 1]
Primer Fila de x2:
[3 5 2 4]


### Subarreglos como vistas sin copia

Los segmentos de arrays devuelven vistas en lugar de copias de los datos del array. 

Esta es un área en la que el corte de arrays NumPy difiere del corte de listas de Python: en las listas, los cortes serán copias. 


Esto quiere decir que si modificamos un subconjunto del array este modifica el original. 

Este comportamiento predeterminado es bastante útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos subyacente.


In [96]:
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[3 5]
 [7 6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 11]]


### Creando copias de arreglos

Esto se puede hacer más fácilmente con el copy() método:

Si ahora modificamos este subarreglo, el arreglo original no se toca:

In [98]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

print(x2)

[[99  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7 11]]


## Remodelación de arreglos ¶

Otro tipo útil de operación es la remodelación de arrays. La forma más flexible de hacerlo es con el reshape. Por ejemplo, si desea poner los números del 1 al 9 en un 3 × 3 cuadrícula, puede hacer lo siguiente: 

In [99]:
onetonine = np.arange(1, 10).reshape((3, 3))
print(onetonine)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Otro patrón de remodelación común es la conversión de una matriz unidimensional en una matriz bidimensional de filas o columnas. Esto se puede hacer con el reshape, o más fácilmente haciendo uso de la palabra clave newaxis dentro de una operación de corte: 

In [102]:
x = np.array([1, 2, 3])

# de unidemensional a 1f*3c  = row vector v
x.reshape((1, 3))


array([[1, 2, 3]])

In [103]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [104]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [105]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenación y división de arreglos ¶

También es posible combinar varios arreglos en uno ó dividir un solo arreglo en varios arreglos.

### Concatenación de arreglos

La concatenación de dos ó más arrays en NumPy, se logra principalmente usando las rutinas:
    
    np.concatenate  =>  Toma una tupla o lista de arrays como primer argumento.
    np.vstack   =>  Trabaja con arrays de dimensiones mixtas verticalmente.
    np.hstack   =>  Trabaja con arrays de dimensiones mixtas horizontalmente.


Del mismo modo, np.dstack  apilará matrices a lo largo del tercer eje.

In [108]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]

print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]


In [110]:
matriz = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([matriz, matriz])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [111]:
np.concatenate([matriz, matriz], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [112]:
x = np.array([1, 2, 3])
matriz = np.array([[9, 8, 7],
                 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, matriz])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [113]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([matriz, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### División de arreglos

La división se implementa por las funciones:
    np.split
    np.hsplit
    np.vsplit

Para cada uno de estos, podemos pasar una lista de índices que dan los puntos de división: 

In [119]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [2, 5])
print(x1, x2, x3)

[1 2] [ 3 99 99] [3 2 1]


Observe que N puntos de división conducen a N + 1 subarreglos. Las funciones relacionadas np.hsplity np.vsplitson similares:

In [116]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [118]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplit dividirá matrices a lo largo del tercer eje.